version: '3.8'

services:
  # Database MySQL
  mysql:
    image: mysql:8.0
    container_name: smartagenda-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: SMARTAGENDA
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./setup_smartagenda.sql:/docker-entrypoint-initdb.d/setup_smartagenda.sql:ro
    networks:
      - smartagenda-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Applicazione SmartAgenda
  smartagenda:
    build: .
    container_name: smartagenda-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=SMARTAGENDA
      - DB_USER=alessandro
      - DB_PASSWORD=studenteEcampus2025
    networks:
      - smartagenda-network
    volumes:
      - app_logs:/var/log/smartagenda

volumes:
  mysql_data:
    driver: local
  app_logs:
    driver: local

networks:
  smartagenda-network:
    driver: bridge 