-- Crea database se non esiste
CREATE DATABASE IF NOT EXISTS SMARTAGENDA DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- Crea utente solo se non esiste
CREATE USER IF NOT EXISTS 'alessandro'@'localhost' IDENTIFIED BY 'studenteEcampus2025';

-- Permessi solo sul database smartagenda
GRANT ALL PRIVILEGES ON SMARTAGENDA.* TO 'alessandro'@'localhost';

FLUSH PRIVILEGES;

-- Tabella utenti
CREATE TABLE IF NOT EXISTS SMARTAGENDA.UTENTI (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(50) UNIQUE NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(100) UNIQUE NOT NULL,
  RUOLO ENUM('ospite', 'utente', 'admin') DEFAULT 'utente',
  DATA_REGISTRAZIONE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ULTIMO_ACCESSO TIMESTAMP NULL,
  ATTIVO BOOLEAN DEFAULT TRUE
);

-- Tabella appuntamenti
CREATE TABLE IF NOT EXISTS SMARTAGENDA.APPUNTAMENTI (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TITOLO VARCHAR(100) NOT NULL,
  DESCRIZIONE TEXT,
  DATA DATETIME NOT NULL,
  ID_UTENTE INT NOT NULL,
  CONDIVISO BOOLEAN DEFAULT FALSE,
  DATA_CREAZIONE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DATA_MODIFICA TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID) ON DELETE CASCADE,
  INDEX IDX_DATA (DATA),
  INDEX IDX_UTENTE (ID_UTENTE)
);

-- Tabella inviti per appuntamenti condivisi
CREATE TABLE IF NOT EXISTS SMARTAGENDA.INVITI (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ID_APPUNTAMENTO INT NOT NULL,
  ID_UTENTE_INVITANTE INT NOT NULL,
  ID_UTENTE_INVITATO INT NOT NULL,
  STATO ENUM('in_attesa', 'accettato', 'rifiutato') DEFAULT 'in_attesa',
  DATA_INVITO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DATA_RISPOSTA TIMESTAMP NULL,
  MESSAGGIO TEXT,
  FOREIGN KEY (ID_APPUNTAMENTO) REFERENCES APPUNTAMENTI(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_UTENTE_INVITANTE) REFERENCES UTENTI(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_UTENTE_INVITATO) REFERENCES UTENTI(ID) ON DELETE CASCADE,
  UNIQUE KEY UNIQUE_INVITO (ID_APPUNTAMENTO, ID_UTENTE_INVITATO)
);

-- Tabella notifiche
CREATE TABLE IF NOT EXISTS SMARTAGENDA.NOTIFICHE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ID_UTENTE INT NOT NULL,
  TITOLO VARCHAR(100) NOT NULL,
  MESSAGGIO TEXT NOT NULL,
  TIPO ENUM('info', 'warning', 'error', 'success') DEFAULT 'info',
  LETTA BOOLEAN DEFAULT FALSE,
  DATA_CREAZIONE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DATA_SCADENZA DATETIME NULL,
  FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID) ON DELETE CASCADE,
  INDEX IDX_UTENTE_LETTA (ID_UTENTE, LETTA)
);

-- Tabella promemoria
CREATE TABLE IF NOT EXISTS SMARTAGENDA.PROMEMORIA (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ID_APPUNTAMENTO INT NOT NULL,
  ID_UTENTE INT NOT NULL,
  MINUTI_PRIMA INT NOT NULL DEFAULT 15,
  ATTIVO BOOLEAN DEFAULT TRUE,
  INVIATO BOOLEAN DEFAULT FALSE,
  DATA_INVIO TIMESTAMP NULL,
  FOREIGN KEY (ID_APPUNTAMENTO) REFERENCES APPUNTAMENTI(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID) ON DELETE CASCADE,
  UNIQUE KEY UNIQUE_PROMEMORIA (ID_APPUNTAMENTO, ID_UTENTE)
);

-- Tabella categorie appuntamenti
CREATE TABLE IF NOT EXISTS SMARTAGENDA.CATEGORIE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(50) NOT NULL,
  COLORE VARCHAR(7) DEFAULT '#007bff',
  ID_UTENTE INT NOT NULL,
  FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID) ON DELETE CASCADE,
  UNIQUE KEY UNIQUE_CATEGORIA_UTENTE (NOME, ID_UTENTE)
);

-- Aggiunge categoria agli appuntamenti
ALTER TABLE SMARTAGENDA.APPUNTAMENTI
  ADD COLUMN ID_CATEGORIA INT NULL, ADD FOREIGN KEY (
    ID_CATEGORIA
  )
    REFERENCES CATEGORIE(
      ID
    ) ON DELETE SET NULL;

-- Inserisce utente amministratore di default
INSERT IGNORE INTO SMARTAGENDA.UTENTI (
  USERNAME,
  PASSWORD,
  EMAIL,
  RUOLO
) VALUES (
  'admin',
  SHA2('admin123', 256),
  'admin@smartagenda.com',
  'admin'
);

-- Inserisce categorie di default per l'admin
INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Lavoro',
    '#dc3545',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'admin';

INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Personale',
    '#28a745',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'admin';

INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Studio',
    '#ffc107',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'admin';

INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Salute',
    '#fd7e14',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'admin';