-- Crea database se non esiste
CREATE DATABASE IF NOT EXISTS SMARTAGENDA DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- Crea utente solo se non esiste (per localhost e per Docker)
CREATE USER IF NOT EXISTS 'alessandro'@'localhost' IDENTIFIED BY 'studenteEcampus2025';

CREATE USER IF NOT EXISTS 'alessandro'@'%' IDENTIFIED BY 'studenteEcampus2025';

-- Permessi solo sul database smartagenda
GRANT ALL PRIVILEGES ON SMARTAGENDA.* TO 'alessandro'@'localhost';

GRANT ALL PRIVILEGES ON SMARTAGENDA.* TO 'alessandro'@'%';

FLUSH PRIVILEGES;

-- Tabella utenti
CREATE TABLE IF NOT EXISTS SMARTAGENDA.UTENTI (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(50) UNIQUE NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(100) UNIQUE NOT NULL,
  RUOLO ENUM('ospite', 'utente', 'admin') DEFAULT 'utente',
  DATA_REGISTRAZIONE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ULTIMO_ACCESSO TIMESTAMP NULL,
  ATTIVO BOOLEAN DEFAULT TRUE
);

-- Tabella appuntamenti
CREATE TABLE IF NOT EXISTS SMARTAGENDA.APPUNTAMENTI (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TITOLO VARCHAR(100) NOT NULL,
  DESCRIZIONE TEXT,
  DATA DATETIME NOT NULL,
  ID_UTENTE INT NOT NULL,
  CONDIVISO BOOLEAN DEFAULT FALSE,
  DATA_CREAZIONE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DATA_MODIFICA TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID) ON DELETE CASCADE,
  INDEX IDX_DATA (DATA),
  INDEX IDX_UTENTE (ID_UTENTE)
);

-- Tabella inviti per appuntamenti condivisi
CREATE TABLE IF NOT EXISTS SMARTAGENDA.INVITI (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ID_APPUNTAMENTO INT NOT NULL,
  ID_UTENTE_INVITANTE INT NOT NULL,
  ID_UTENTE_INVITATO INT NOT NULL,
  STATO ENUM('in_attesa', 'accettato', 'rifiutato') DEFAULT 'in_attesa',
  DATA_INVITO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DATA_RISPOSTA TIMESTAMP NULL,
  MESSAGGIO TEXT,
  FOREIGN KEY (ID_APPUNTAMENTO) REFERENCES APPUNTAMENTI(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_UTENTE_INVITANTE) REFERENCES UTENTI(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_UTENTE_INVITATO) REFERENCES UTENTI(ID) ON DELETE CASCADE,
  UNIQUE KEY UNIQUE_INVITO (ID_APPUNTAMENTO, ID_UTENTE_INVITATO)
);

-- Tabella notifiche
CREATE TABLE IF NOT EXISTS SMARTAGENDA.NOTIFICHE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ID_UTENTE INT NOT NULL,
  TITOLO VARCHAR(100) NOT NULL,
  MESSAGGIO TEXT NOT NULL,
  TIPO ENUM('info', 'warning', 'error', 'success') DEFAULT 'info',
  LETTA BOOLEAN DEFAULT FALSE,
  DATA_CREAZIONE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DATA_SCADENZA DATETIME NULL,
  FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID) ON DELETE CASCADE,
  INDEX IDX_UTENTE_LETTA (ID_UTENTE, LETTA)
);

-- Tabella promemoria
CREATE TABLE IF NOT EXISTS SMARTAGENDA.PROMEMORIA (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ID_APPUNTAMENTO INT NOT NULL,
  ID_UTENTE INT NOT NULL,
  MINUTI_PRIMA INT NOT NULL DEFAULT 15,
  ATTIVO BOOLEAN DEFAULT TRUE,
  INVIATO BOOLEAN DEFAULT FALSE,
  DATA_INVIO TIMESTAMP NULL,
  FOREIGN KEY (ID_APPUNTAMENTO) REFERENCES APPUNTAMENTI(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID) ON DELETE CASCADE,
  UNIQUE KEY UNIQUE_PROMEMORIA (ID_APPUNTAMENTO, ID_UTENTE)
);

-- Tabella categorie appuntamenti
CREATE TABLE IF NOT EXISTS SMARTAGENDA.CATEGORIE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(50) NOT NULL,
  COLORE VARCHAR(7) DEFAULT '#007bff',
  ID_UTENTE INT NOT NULL,
  FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID) ON DELETE CASCADE,
  UNIQUE KEY UNIQUE_CATEGORIA_UTENTE (NOME, ID_UTENTE)
);

-- Aggiunge categoria agli appuntamenti
ALTER TABLE SMARTAGENDA.APPUNTAMENTI
  ADD COLUMN ID_CATEGORIA INT NULL, ADD FOREIGN KEY (
    ID_CATEGORIA
  )
    REFERENCES CATEGORIE(
      ID
    ) ON DELETE SET NULL;

-- Inserisce utente amministratore di default
INSERT IGNORE INTO SMARTAGENDA.UTENTI (
  USERNAME,
  PASSWORD,
  EMAIL,
  RUOLO
) VALUES (
  'admin',
  SHA2('admin123', 256),
  'admin@smartagenda.com',
  'admin'
);

-- Inserisce utenti demo
INSERT IGNORE INTO SMARTAGENDA.UTENTI (
  USERNAME,
  PASSWORD,
  EMAIL,
  RUOLO
) VALUES (
  'tizio',
  SHA2('tizio123', 256),
  'tizio@smartagenda.com',
  'utente'
);

INSERT IGNORE INTO SMARTAGENDA.UTENTI (
  USERNAME,
  PASSWORD,
  EMAIL,
  RUOLO
) VALUES (
  'caio',
  SHA2('caio123', 256),
  'caio@smartagenda.com',
  'utente'
);

INSERT IGNORE INTO SMARTAGENDA.UTENTI (
  USERNAME,
  PASSWORD,
  EMAIL,
  RUOLO
) VALUES (
  'sempronio',
  SHA2('sempronio123', 256),
  'sempronio@smartagenda.com',
  'utente'
);

-- Inserisce categorie di default per l'admin
INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Lavoro',
    '#dc3545',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'admin';

INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Personale',
    '#28a745',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'admin';

INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Studio',
    '#ffc107',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'admin';

INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Salute',
    '#fd7e14',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'admin';

-- Categorie per utente tizio
INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Lavoro',
    '#007bff',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'tizio';

INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Sport',
    '#20c997',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'tizio';

INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Famiglia',
    '#e83e8c',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'tizio';

-- Categorie per utente caio
INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Università',
    '#6610f2',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'caio';

INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Hobby',
    '#fd7e14',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'caio';

INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Medico',
    '#dc3545',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'caio';

-- Categorie per utente sempronio
INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Lavoro',
    '#495057',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'sempronio';

INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Viaggi',
    '#17a2b8',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'sempronio';

INSERT IGNORE INTO SMARTAGENDA.CATEGORIE (
  NOME,
  COLORE,
  ID_UTENTE
)
  SELECT
    'Casa',
    '#28a745',
    ID
  FROM
    SMARTAGENDA.UTENTI
  WHERE
    USERNAME = 'sempronio';

-- Appuntamenti demo per l'utente tizio
INSERT IGNORE INTO SMARTAGENDA.APPUNTAMENTI (
  TITOLO,
  DESCRIZIONE,
  DATA,
  ID_UTENTE,
  CONDIVISO,
  ID_CATEGORIA
) VALUES (
  'Riunione di lavoro',
  'Presentazione progetto Q4',
  DATE_ADD(NOW(), INTERVAL 2 DAY),
  (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'tizio'),
  TRUE,
  (SELECT ID FROM SMARTAGENDA.CATEGORIE WHERE NOME = 'Lavoro' AND ID_UTENTE = (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'tizio'))
);

INSERT IGNORE INTO SMARTAGENDA.APPUNTAMENTI (
  TITOLO,
  DESCRIZIONE,
  DATA,
  ID_UTENTE,
  CONDIVISO,
  ID_CATEGORIA
) VALUES (
  'Allenamento palestra',
  'Sessione di allenamento settimanale',
  DATE_ADD(NOW(), INTERVAL 1 DAY),
  (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'tizio'),
  FALSE,
  (SELECT ID FROM SMARTAGENDA.CATEGORIE WHERE NOME = 'Sport' AND ID_UTENTE = (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'tizio'))
);

INSERT IGNORE INTO SMARTAGENDA.APPUNTAMENTI (
  TITOLO,
  DESCRIZIONE,
  DATA,
  ID_UTENTE,
  CONDIVISO,
  ID_CATEGORIA
) VALUES (
  'Cena con la famiglia',
  'Cena domenicale dai nonni',
  DATE_ADD(NOW(), INTERVAL 3 DAY),
  (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'tizio'),
  FALSE,
  (SELECT ID FROM SMARTAGENDA.CATEGORIE WHERE NOME = 'Famiglia' AND ID_UTENTE = (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'tizio'))
);

-- Appuntamenti demo per caio
INSERT IGNORE INTO SMARTAGENDA.APPUNTAMENTI (
  TITOLO,
  DESCRIZIONE,
  DATA,
  ID_UTENTE,
  CONDIVISO,
  ID_CATEGORIA
) VALUES (
  'Esame di Matematica',
  'Esame del corso di Analisi Matematica',
  DATE_ADD(NOW(), INTERVAL 5 DAY),
  (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'caio'),
  FALSE,
  (SELECT ID FROM SMARTAGENDA.CATEGORIE WHERE NOME = 'Università' AND ID_UTENTE = (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'caio'))
);

INSERT IGNORE INTO SMARTAGENDA.APPUNTAMENTI (
  TITOLO,
  DESCRIZIONE,
  DATA,
  ID_UTENTE,
  CONDIVISO,
  ID_CATEGORIA
) VALUES (
  'Corso di chitarra',
  'Lezione settimanale di chitarra',
  DATE_ADD(NOW(), INTERVAL 1 DAY),
  (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'caio'),
  TRUE,
  (SELECT ID FROM SMARTAGENDA.CATEGORIE WHERE NOME = 'Hobby' AND ID_UTENTE = (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'caio'))
);

INSERT IGNORE INTO SMARTAGENDA.APPUNTAMENTI (
  TITOLO,
  DESCRIZIONE,
  DATA,
  ID_UTENTE,
  CONDIVISO,
  ID_CATEGORIA
) VALUES (
  'Visita medica',
  'Controllo generale annuale',
  DATE_ADD(NOW(), INTERVAL 7 DAY),
  (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'caio'),
  FALSE,
  (SELECT ID FROM SMARTAGENDA.CATEGORIE WHERE NOME = 'Medico' AND ID_UTENTE = (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'caio'))
);

-- Appuntamenti demo per sempronio
INSERT IGNORE INTO SMARTAGENDA.APPUNTAMENTI (
  TITOLO,
  DESCRIZIONE,
  DATA,
  ID_UTENTE,
  CONDIVISO,
  ID_CATEGORIA
) VALUES (
  'Meeting clienti',
  'Presentazione nuovo prodotto',
  DATE_ADD(NOW(), INTERVAL 2 DAY),
  (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'sempronio'),
  TRUE,
  (SELECT ID FROM SMARTAGENDA.CATEGORIE WHERE NOME = 'Lavoro' AND ID_UTENTE = (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'sempronio'))
);

INSERT IGNORE INTO SMARTAGENDA.APPUNTAMENTI (
  TITOLO,
  DESCRIZIONE,
  DATA,
  ID_UTENTE,
  CONDIVISO,
  ID_CATEGORIA
) VALUES (
  'Prenotazione viaggio',
  'Organizzare vacanze estive',
  DATE_ADD(NOW(), INTERVAL 4 DAY),
  (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'sempronio'),
  FALSE,
  (SELECT ID FROM SMARTAGENDA.CATEGORIE WHERE NOME = 'Viaggi' AND ID_UTENTE = (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'sempronio'))
);

INSERT IGNORE INTO SMARTAGENDA.APPUNTAMENTI (
  TITOLO,
  DESCRIZIONE,
  DATA,
  ID_UTENTE,
  CONDIVISO,
  ID_CATEGORIA
) VALUES (
  'Pulizie di primavera',
  'Riorganizzazione armadi e pulizie',
  DATE_ADD(NOW(), INTERVAL 6 DAY),
  (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'sempronio'),
  FALSE,
  (SELECT ID FROM SMARTAGENDA.CATEGORIE WHERE NOME = 'Casa' AND ID_UTENTE = (SELECT ID FROM SMARTAGENDA.UTENTI WHERE USERNAME = 'sempronio'))
);